---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Promessa sem jeito!
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O código de um programa em Python
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O código de um programa em Java
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Um `txt` com uma lista de compras
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Um vídeo de 3 %
  checked: false
name: Não só de HTML se vive
