---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Tres empanadas
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El código de un programa en Ruby
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: El código de un programa en Java
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Un `txt` con una lista de compras
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Un video de los Simuladores
  checked: false
name: No se vive sólo de HTML
